### ISSUE TITLE
ISAAC

### ISSUE THREAD

**Issue by ysbaddaden** [scidom/random.cr#2]
I notice you want to add support for ISAAC. I just wanted to point out that it's already available in crystal stdlib: https://github.com/manastech/crystal/blob/master/src/random/isaac.cr

**Comment by scidom** [comment]
Thanks, @ysbaddaden, I don't maintain this repo anymore. Given the conflict with stdlib (see also issue #1), I will withdraw the repo to avoid causing confusiong.
